@extends('tenant.layouts.bom')

@section('title', 'Create BOM')
@section('page-title', 'Create New Bill of Materials')

@push('head')
<meta name="csrf-token" content="{{ csrf_token() }}">
@endpush

@section('content')
<div x-data="bomForm()" x-init="loadDropdowns()">
    <div class="max-w-4xl mx-auto">
        <!-- Header -->
        <div class="bg-white rounded-xl shadow p-6 mb-6">
            <div class="flex items-center justify-between">
                <div>
                    <h2 class="text-2xl font-bold text-gray-900">Create New Bill of Materials</h2>
                    <p class="text-gray-600 mt-1">Define product BOM with version management</p>
                </div>
                <a href="{{ url(request()->get('tenant_type') === 'subdomain' ? '/bom-header' : '/org/' . $organization->org_slug . '/bom-header') }}" 
                   class="px-4 py-2 border border-gray-300 rounded-lg hover:bg-gray-50 transition-colors">
                    <i class="fas fa-arrow-left mr-2"></i>Back to List
                </a>
            </div>
        </div>

        <!-- Form -->
        <form @submit.prevent="submitForm" class="bg-white rounded-xl shadow p-6">
            <!-- BOM Information -->
            <div class="mb-6">
                <h3 class="text-lg font-semibold text-gray-900 mb-4 pb-2 border-b">BOM Header Information</h3>
                <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
                    <!-- BOM Code -->
                    <div class="md:col-span-2">
                        <label class="block text-sm font-medium text-gray-700 mb-2">
                            BOM Code <span class="text-red-500" x-show="!form.auto_generate_code">*</span>
                        </label>
                        <div class="space-y-3">
                            <!-- Auto-generate option -->
                            <div class="flex items-center space-x-3">
                                <input type="checkbox" 
                                       x-model="form.auto_generate_code"
                                       @change="handleAutoGenerateChange()"
                                       class="w-4 h-4 text-blue-600 border-gray-300 rounded focus:ring-blue-500">
                                <label class="text-sm text-gray-700 cursor-pointer">Auto-generate BOM code</label>
                            </div>
                            
                            <!-- Manual code input -->
                            <div x-show="!form.auto_generate_code" x-transition>
                                <input type="text" 
                                       x-model="form.bom_code"
                                       :required="!form.auto_generate_code"
                                       maxlength="50"
                                       placeholder="BOM-0001"
                                       class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent">
                                <p class="text-xs text-gray-500 mt-1">Unique BOM identifier</p>
                            </div>
                            
                            <!-- Auto-generate info -->
                            <div x-show="form.auto_generate_code" x-transition>
                                <div class="bg-blue-50 border border-blue-200 rounded-lg p-3">
                                    <p class="text-sm text-blue-800">
                                        <i class="fas fa-info-circle mr-1"></i>
                                        BOM code will be auto-generated by the system (BOM-0001, BOM-0002, etc.)
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>

                    <!-- Product -->
                    <div>
                        <label class="block text-sm font-medium text-gray-700 mb-2">
                            Product <span class="text-red-500">*</span>
                        </label>
                        <select x-model="form.product_id" required
                                class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent">
                            <option value="">Select Product</option>
                            <template x-for="product in products" :key="product.id">
                                <option :value="product.id" x-text="product.product_code + ' - ' + product.product_name"></option>
                            </template>
                        </select>
                        <p class="text-xs text-gray-500 mt-1">→ product_master(product_id)</p>
                    </div>

                    <!-- BOM Version -->
                    <div>
                        <label class="block text-sm font-medium text-gray-700 mb-2">
                            BOM Version
                        </label>
                        <input type="text" x-model="form.bom_version" maxlength="20"
                               placeholder="v1.0"
                               class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent">
                        <p class="text-xs text-gray-500 mt-1">Version identifier (default: v1.0)</p>
                    </div>

                    <!-- BOM Description -->
                    <div class="md:col-span-2">
                        <label class="block text-sm font-medium text-gray-700 mb-2">
                            BOM Description
                        </label>
                        <textarea x-model="form.bom_description" rows="2" maxlength="500"
                                  placeholder="Description of this BOM..."
                                  class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"></textarea>
                        <p class="text-xs text-gray-500 mt-1">Optional description</p>
                    </div>

                    <!-- Effective From -->
                    <div>
                        <label class="block text-sm font-medium text-gray-700 mb-2">
                            Effective From <span class="text-red-500">*</span>
                        </label>
                        <input type="date" x-model="form.effective_from" required
                               class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent">
                        <p class="text-xs text-gray-500 mt-1">BOM valid from this date</p>
                    </div>

                    <!-- Effective To -->
                    <div>
                        <label class="block text-sm font-medium text-gray-700 mb-2">
                            Effective To
                        </label>
                        <input type="date" x-model="form.effective_to"
                               class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent">
                        <p class="text-xs text-gray-500 mt-1">NULL = currently active BOM</p>
                    </div>

                    <!-- Batch Size -->
                    <div>
                        <label class="block text-sm font-medium text-gray-700 mb-2">
                            Batch Size
                        </label>
                        <input type="number" x-model="form.batch_size" min="0" step="0.001"
                               placeholder="1"
                               class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent">
                        <p class="text-xs text-gray-500 mt-1">Output quantity per batch (default: 1)</p>
                    </div>
                </div>
            </div>

            <!-- Status Flags -->
            <div class="mb-6">
                <h3 class="text-lg font-semibold text-gray-900 mb-4 pb-2 border-b">Status</h3>
                <div class="space-y-3">
                    <label class="flex items-center space-x-3">
                        <input type="checkbox" x-model="form.is_active" class="w-5 h-5 text-blue-600 border-gray-300 rounded focus:ring-2 focus:ring-blue-500">
                        <span class="text-sm font-medium text-gray-700">Active BOM</span>
                    </label>
                    <label class="flex items-center space-x-3">
                        <input type="checkbox" x-model="form.is_approved" class="w-5 h-5 text-green-600 border-gray-300 rounded focus:ring-2 focus:ring-green-500">
                        <span class="text-sm font-medium text-gray-700">Approved for Production</span>
                    </label>
                </div>
            </div>

            <!-- Remarks -->
            <div class="mb-6" x-show="false">
                <label class="block text-sm font-medium text-gray-700 mb-2">
                    Remarks
                </label>
                <textarea x-model="form.remarks" rows="3"
                          placeholder="Change notes, reason for version..."
                          class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"></textarea>
                <p class="text-xs text-gray-500 mt-1">Change notes, reason for version</p>
            </div>

            <!-- Info Box -->
            <div class="bg-blue-50 border border-blue-200 rounded-lg p-4 mb-6">
                <div class="flex items-start">
                    <i class="fas fa-info-circle text-blue-600 mt-1 mr-3"></i>
                    <div class="text-sm text-blue-800">
                        <p class="font-semibold mb-1">About BOM Header</p>
                        <p>Bill of Materials header with version management. Replaces the flat bom_master table. Supports multiple BOM versions per product with effective date ranges.</p>
                        <p class="mt-2 text-xs">Used in: Production Work Orders, MRP, Material Planning, Costing</p>
                        <p class="mt-1 text-xs font-semibold">Unique Constraint: (product_id, version)</p>
                    </div>
                </div>
            </div>

            <!-- Form Actions -->
            <div class="flex items-center justify-end space-x-4 pt-6 border-t">
                <a href="{{ url(request()->get('tenant_type') === 'subdomain' ? '/bom-header' : '/org/' . $organization->org_slug . '/bom-header') }}" 
                   class="px-6 py-2 border border-gray-300 rounded-lg hover:bg-gray-50 transition-colors">
                    Cancel
                </a>
                <button type="submit" :disabled="loading"
                        class="px-6 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors disabled:opacity-50 disabled:cursor-not-allowed">
                    <span x-show="!loading">Create BOM</span>
                    <span x-show="loading"><i class="fas fa-spinner fa-spin mr-2"></i>Creating...</span>
                </button>
            </div>
        </form>
    </div>
</div>

<script>
function bomForm() {
    return {
        loading: false,
        products: [],
        form: {
            bom_code: '',
            bom_version: 'v1.0',
            product_id: '',
            bom_description: '',
            effective_from: '',
            effective_to: '',
            batch_size: 1,
            is_active: true,
            is_approved: false,
            auto_generate_code: false
        },
        
        handleAutoGenerateChange() {
            if (this.form.auto_generate_code) {
                this.form.bom_code = '';
            }
        },
        
        async loadDropdowns() {
            try {
                // Load products
                const productResponse = await fetch('/api/v1/products?per_page=1000&is_active=1', {
                    credentials: 'same-origin',
                    headers: { 'Accept': 'application/json' }
                });
                
                if (productResponse.ok) {
                    const productData = await productResponse.json();
                    if (productData && productData.success && productData.data) {
                        this.products = productData.data.products || [];
                    }
                }
            } catch (error) {
                console.error('Failed to load products:', error);
                alert('Failed to load products. Please refresh the page.');
            }
        },
        
        async submitForm() {
            this.loading = true;
            try {
                // Prepare form data
                const submitData = { ...this.form };
                delete submitData.auto_generate_code;
                
                // If auto-generate is enabled, don't send bom_code
                if (this.form.auto_generate_code) {
                    delete submitData.bom_code;
                }
                
                const response = await fetch('/api/v1/bom-headers', {
                    method: 'POST',
                    credentials: 'same-origin',
                    headers: {
                        'Content-Type': 'application/json',
                        'Accept': 'application/json',
                        'X-CSRF-TOKEN': document.querySelector('meta[name="csrf-token"]').getAttribute('content')
                    },
                    body: JSON.stringify(submitData)
                });
                
                const data = await response.json();
                
                if (!response.ok || !data || data.success !== true) {
                    throw new Error((data && data.message) ? data.message : 'Failed to create BOM');
                }
                
                alert('BOM header created successfully!');
                window.location.href = '{{ url(request()->get('tenant_type') === 'subdomain' ? '/bom-header' : '/org/' . $organization->org_slug . '/bom-header') }}';
            } catch (error) {
                console.error('Failed to create BOM:', error);
                alert(error.message || 'Failed to create BOM. Please try again.');
            } finally {
                this.loading = false;
            }
        }
    }
}
</script>
@endsection
