@extends('layouts.procurement')

@section('title', 'Edit Purchase Requisition')
@section('page-title', 'Edit Purchase Requisition')

@section('content')
<div x-data="editPR()" x-init="init()">

    <!-- PR Number Modal -->
    <div x-show="showPrModal" x-cloak class="fixed inset-0 z-50 flex items-center justify-center" style="display:none;">
        <div class="fixed inset-0 bg-gray-900 bg-opacity-50" @click="showPrModal = false"></div>
        <div class="relative bg-white rounded-xl shadow-xl p-8 w-full max-w-sm text-center z-10">
            <p class="text-sm text-gray-500 mb-2">Purchase Requisition Number</p>
            <p class="text-3xl font-bold text-primary tracking-widest" x-text="prNumber"></p>
            <p class="text-xs text-gray-400 mt-3">Auto-generated by system</p>
            <button @click="showPrModal = false"
                class="mt-6 px-6 py-2 bg-primary text-white rounded-lg hover:bg-primary/90 transition-colors">
                Close
            </button>
        </div>
    </div>

    <div class="max-w-6xl mx-auto">
        <!-- Header -->
        <div class="bg-white rounded-xl shadow p-6 mb-6">
            <div class="flex items-center justify-between">
                <div>
                    <h2 class="text-2xl font-bold text-gray-900">Edit Purchase Requisition</h2>
                    <p class="text-gray-600 mt-1 flex items-center gap-2">
                        <span x-text="prNumber" class="font-semibold text-blue-600"></span>
                        <button @click="showPrModal = true" class="text-gray-400 hover:text-blue-600" title="View PR Number">
                            <span class="material-symbols-outlined text-base">visibility</span>
                        </button>
                    </p>
                </div>
                <a href="{{ url("/org/{$organization->org_slug}/procurement/purchase-requisition") }}"
                    class="px-4 py-2 border border-gray-300 rounded-lg hover:bg-gray-50 transition-colors flex items-center gap-2">
                    <span class="material-symbols-outlined text-sm">arrow_back</span>Back to List
                </a>
            </div>
        </div>

        <!-- Loading -->
        <div x-show="masterLoading" class="bg-white rounded-xl shadow p-12 text-center">
            <div class="animate-spin rounded-full h-10 w-10 border-b-2 border-primary mx-auto mb-4"></div>
            <p class="text-gray-500">Loading form data...</p>
        </div>

        <!-- Form -->
        <form x-show="!masterLoading" @submit.prevent="submitForm('PENDING_APPROVAL')" class="space-y-6">

            <!-- Basic Information -->
            <div class="bg-white rounded-xl shadow p-6">
                <h3 class="text-lg font-semibold text-gray-900 mb-4 pb-2 border-b">Basic Information</h3>
                <div class="grid grid-cols-1 md:grid-cols-2 gap-6">

                    <div>
                        <label class="block text-sm font-medium text-gray-700 mb-2">PR Date</label>
                        <input type="date" x-model="form.pr_date" readonly
                            class="w-full px-4 py-2 border border-gray-200 rounded-lg bg-gray-50 text-gray-600">
                    </div>

                    <div>
                        <label class="block text-sm font-medium text-gray-700 mb-2">Status</label>
                        <span class="block px-3 py-2 rounded-lg text-sm font-semibold bg-gray-100 text-gray-700 text-center"
                            x-text="form.status"></span>
                    </div>

                    <div>
                        <label class="block text-sm font-medium text-gray-700 mb-2">Requested By <span class="text-red-500">*</span></label>
                        <select x-model="form.requested_by" required
                            class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary/20 focus:border-primary">
                            <option value="">Select Employee</option>
                            <template x-for="u in users" :key="u.id">
                                <option :value="String(u.id)" x-text="u.first_name + ' ' + u.last_name + ' (' + u.employee_code + ')'"></option>
                            </template>
                        </select>
                    </div>

                    <div>
                        <label class="block text-sm font-medium text-gray-700 mb-2">Department <span class="text-red-500">*</span></label>
                        <select x-model="form.department_id" required @change="onDeptChange()"
                            class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary/20 focus:border-primary">
                            <option value="">Select Department</option>
                            <template x-for="d in departments" :key="d.id">
                                <option :value="String(d.id)" x-text="d.dept_name"></option>
                            </template>
                        </select>
                    </div>

                    <div>
                        <label class="block text-sm font-medium text-gray-700 mb-2">Cost Center Code</label>
                        <input type="text" x-model="form.cost_center_code" readonly placeholder="Auto-filled from department"
                            class="w-full px-4 py-2 border border-gray-200 rounded-lg bg-gray-50 text-gray-600">
                    </div>

                    <div>
                        <label class="block text-sm font-medium text-gray-700 mb-2">Required Date <span class="text-red-500">*</span></label>
                        <input type="date" x-model="form.required_date" required
                            class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary/20 focus:border-primary">
                    </div>

                    <div>
                        <label class="block text-sm font-medium text-gray-700 mb-2">Priority <span class="text-red-500">*</span></label>
                        <select x-model="form.priority" required
                            class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary/20 focus:border-primary">
                            <option value="">Select Priority</option>
                            <option value="LOW">Low</option>
                            <option value="MEDIUM">Medium</option>
                            <option value="HIGH">High</option>
                            <option value="EMERGENCY">Emergency</option>
                        </select>
                    </div>

                    <div>
                        <label class="block text-sm font-medium text-gray-700 mb-2">Budget Code</label>
                        <input type="text" x-model="form.budget_code" maxlength="50" placeholder="GL account / budget code"
                            class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary/20 focus:border-primary">
                    </div>

                    <div>
                        <label class="block text-sm font-medium text-gray-700 mb-2">Suggested Vendor</label>
                        <select x-model="form.suggested_vendor_id"
                            class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary/20 focus:border-primary">
                            <option value="">None (Optional)</option>
                            <template x-for="v in vendors" :key="v.id">
                                <option :value="v.id" x-text="v.vendor_name"></option>
                            </template>
                        </select>
                    </div>
                </div>

                <div class="mt-6">
                    <label class="block text-sm font-medium text-gray-700 mb-2">Justification</label>
                    <textarea x-model="form.justification" rows="3" placeholder="Business reason..."
                        class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary/20 focus:border-primary"></textarea>
                </div>

                <div class="mt-4">
                    <label class="block text-sm font-medium text-gray-700 mb-2">Remarks</label>
                    <textarea x-model="form.remarks" rows="2" placeholder="Internal notes..."
                        class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary/20 focus:border-primary"></textarea>
                </div>
            </div>

            <!-- Line Items -->
            <div class="bg-white rounded-xl shadow p-6">
                <div class="flex items-center justify-between mb-4 pb-2 border-b">
                    <h3 class="text-lg font-semibold text-gray-900">
                        Line Items
                        <span class="ml-2 text-sm font-normal text-gray-500"
                            x-text="'(' + form.line_items.length + ' item' + (form.line_items.length !== 1 ? 's' : '') + ')'"></span>
                    </h3>
                    <button type="button" @click="addLineItem()"
                        class="px-4 py-2 bg-primary text-white rounded-lg hover:bg-primary/90 transition-colors flex items-center gap-2">
                        <span class="material-symbols-outlined text-sm">add</span>Add Item
                    </button>
                </div>

                <template x-if="form.line_items.length === 0">
                    <div class="text-center py-12 text-gray-400">
                        <span class="material-symbols-outlined text-5xl mb-3">inventory_2</span>
                        <p class="text-sm">No items. Click "Add Item" to start.</p>
                    </div>
                </template>

                <div class="space-y-4">
                    <template x-for="(item, index) in form.line_items" :key="index">
                        <div class="border border-gray-200 rounded-xl p-5 bg-gray-50">
                            <div class="flex items-center justify-between mb-4">
                                <span class="text-sm font-semibold text-gray-700 bg-white border border-gray-200 px-3 py-1 rounded-full"
                                    x-text="'Line ' + (index + 1)"></span>
                                <button type="button" @click="removeLineItem(index)"
                                    class="text-red-500 hover:text-red-700 flex items-center gap-1 text-sm">
                                    <span class="material-symbols-outlined text-base">delete</span>Remove
                                </button>
                            </div>
                            <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                                <div class="lg:col-span-2">
                                    <label class="block text-xs font-medium text-gray-600 mb-1">Material <span class="text-gray-400">(auto-fills fields)</span></label>
                                    <select x-model="item.material_id" @change="onMaterialSelect(index)"
                                        class="w-full px-3 py-2 border border-gray-300 rounded-lg text-sm focus:ring-2 focus:ring-primary/20 focus:border-primary bg-white">
                                        <option value="">Select Material</option>
                                        <template x-for="m in materials" :key="m.id">
                                            <option :value="m.id" x-text="m.material_code + ' — ' + m.material_name"></option>
                                        </template>
                                    </select>
                                </div>
                                <div>
                                    <label class="block text-xs font-medium text-gray-600 mb-1">Material Type</label>
                                    <input type="text" x-model="item.material_type" readonly placeholder="Auto-filled"
                                        class="w-full px-3 py-2 border border-gray-200 rounded-lg text-sm bg-white text-gray-500">
                                </div>
                                <div class="lg:col-span-2">
                                    <label class="block text-xs font-medium text-gray-600 mb-1">Item Name <span class="text-red-500">*</span></label>
                                    <input type="text" x-model="item.item_name" required maxlength="200"
                                        class="w-full px-3 py-2 border border-gray-300 rounded-lg text-sm focus:ring-2 focus:ring-primary/20 focus:border-primary bg-white">
                                </div>
                                <div>
                                    <label class="block text-xs font-medium text-gray-600 mb-1">Quantity <span class="text-red-500">*</span></label>
                                    <input type="number" x-model="item.quantity" required min="0.001" step="0.001" @input="calcTotal(index)"
                                        class="w-full px-3 py-2 border border-gray-300 rounded-lg text-sm focus:ring-2 focus:ring-primary/20 focus:border-primary bg-white">
                                </div>
                                <div>
                                    <label class="block text-xs font-medium text-gray-600 mb-1">UOM <span class="text-red-500">*</span></label>
                                    <select x-model="item.uom_id" required
                                        class="w-full px-3 py-2 border border-gray-300 rounded-lg text-sm focus:ring-2 focus:ring-primary/20 focus:border-primary bg-white">
                                        <option value="">Select UOM</option>
                                        <template x-for="u in uoms" :key="u.id">
                                            <option :value="u.id" x-text="u.uom_name"></option>
                                        </template>
                                    </select>
                                </div>
                                <div>
                                    <label class="block text-xs font-medium text-gray-600 mb-1">Est. Unit Price</label>
                                    <input type="number" x-model="item.estimated_unit_price" step="0.0001" min="0" @input="calcTotal(index)"
                                        class="w-full px-3 py-2 border border-gray-300 rounded-lg text-sm focus:ring-2 focus:ring-primary/20 focus:border-primary bg-white">
                                </div>
                                <div>
                                    <label class="block text-xs font-medium text-gray-600 mb-1">Est. Total</label>
                                    <input type="text" readonly :value="formatCurrency(item.estimated_total)"
                                        class="w-full px-3 py-2 border border-gray-200 rounded-lg text-sm bg-white text-gray-600 font-semibold">
                                </div>
                                <div>
                                    <label class="block text-xs font-medium text-gray-600 mb-1">Delivery Warehouse</label>
                                    <select x-model="item.warehouse_id"
                                        class="w-full px-3 py-2 border border-gray-300 rounded-lg text-sm focus:ring-2 focus:ring-primary/20 focus:border-primary bg-white">
                                        <option value="">Select Warehouse</option>
                                        <template x-for="w in warehouses" :key="w.id">
                                            <option :value="w.id" x-text="w.warehouse_name"></option>
                                        </template>
                                    </select>
                                </div>
                                <div class="lg:col-span-2">
                                    <label class="block text-xs font-medium text-gray-600 mb-1">Description <span class="text-red-500">*</span></label>
                                    <textarea x-model="item.description" required rows="2"
                                        class="w-full px-3 py-2 border border-gray-300 rounded-lg text-sm focus:ring-2 focus:ring-primary/20 focus:border-primary bg-white"></textarea>
                                </div>
                                <div>
                                    <label class="block text-xs font-medium text-gray-600 mb-1">Purpose</label>
                                    <textarea x-model="item.purpose" rows="2" maxlength="500"
                                        class="w-full px-3 py-2 border border-gray-300 rounded-lg text-sm focus:ring-2 focus:ring-primary/20 focus:border-primary bg-white"></textarea>
                                </div>
                            </div>
                        </div>
                    </template>
                </div>

                <div x-show="form.line_items.length > 0" class="mt-6 pt-4 border-t flex justify-end">
                    <div class="bg-primary/5 border border-primary/20 rounded-xl px-6 py-4 text-right">
                        <p class="text-sm text-gray-500 mb-1">Estimated Grand Total</p>
                        <p class="text-2xl font-bold text-primary" x-text="formatCurrency(grandTotal())"></p>
                    </div>
                </div>
            </div>

            <div x-show="errorMsg" class="bg-red-50 border border-red-200 rounded-xl p-4 text-red-700 text-sm" x-text="errorMsg"></div>

            <!-- Actions -->
            <div class="bg-white rounded-xl shadow p-6">
                <div class="flex items-center justify-end gap-3">
                    <a href="{{ url("/org/{$organization->org_slug}/procurement/purchase-requisition") }}"
                        class="px-6 py-2 border border-gray-300 rounded-lg hover:bg-gray-50 transition-colors">Cancel</a>
                    <button type="button" @click="submitForm('DRAFT')" :disabled="saving"
                        class="px-6 py-2 bg-gray-600 text-white rounded-lg hover:bg-gray-700 transition-colors disabled:opacity-50">
                        <span x-show="!saving">Save as Draft</span>
                        <span x-show="saving" class="flex items-center gap-2">
                            <span class="animate-spin material-symbols-outlined text-sm">refresh</span>Saving...
                        </span>
                    </button>
                    <button type="submit" :disabled="saving || form.line_items.length === 0"
                        class="px-6 py-2 bg-primary text-white rounded-lg hover:bg-primary/90 transition-colors disabled:opacity-50">
                        <span x-show="!saving">Submit for Approval</span>
                        <span x-show="saving" class="flex items-center gap-2">
                            <span class="animate-spin material-symbols-outlined text-sm">refresh</span>Submitting...
                        </span>
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>

<script>
function editPR() {
    return {
        prId: {{ $prId }},
        prNumber: '',
        masterLoading: true,
        saving: false,
        errorMsg: '',
        showPrModal: false,

        users: [], departments: [], vendors: [], materials: [], uoms: [], warehouses: [],

        form: {
            pr_date: '', status: 'DRAFT', requested_by: '', department_id: '',
            cost_center_code: '', required_date: '', priority: 'LOW',
            budget_code: '', suggested_vendor_id: '', justification: '', remarks: '',
            line_items: [],
        },

        async init() {
            await Promise.all([
                this.load('/api/v1/purchase-requisitions/master/users',     r => this.users      = r.data?.users      || []),
                this.load('/api/v1/departments',                             r => this.departments = r.data?.departments || []),
                this.load('/api/v1/vendors',                                 r => this.vendors    = r.data?.vendors    || []),
                this.load('/api/v1/purchase-requisitions/master/materials',  r => this.materials  = r.data?.materials  || []),
                this.load('/api/v1/purchase-requisitions/master/uoms',       r => this.uoms       = r.data?.uoms       || []),
                this.load('/api/v1/purchase-requisitions/master/warehouses', r => this.warehouses = r.data?.warehouses || []),
            ]);
            await this.loadPR();
            this.masterLoading = false;
        },

        async load(url, setter) {
            try {
                const res = await fetch(url, { credentials: 'same-origin', headers: { 'Accept': 'application/json' } });
                if (res.ok) setter(await res.json());
            } catch (e) { console.error('Failed to load', url, e); }
        },

        async loadPR() {
            try {
                const res = await fetch('/api/v1/purchase-requisitions/' + this.prId, {
                    credentials: 'same-origin',
                    headers: { 'Accept': 'application/json' }
                });
                const json = await res.json();
                if (json.success) {
                    const pr = json.data.purchase_requisition;
                    this.prNumber = pr.pr_number;
                    this.form = {
                        pr_date:             this.toDateInput(pr.pr_date),
                        status:              pr.status,
                        requested_by:        pr.requested_by ? String(pr.requested_by) : '',
                        department_id:       pr.department_id ? String(pr.department_id) : '',
                        cost_center_code:    pr.cost_center_code || '',
                        required_date:       this.toDateInput(pr.required_date),
                        priority:            pr.priority,
                        budget_code:         pr.budget_code || '',
                        suggested_vendor_id: pr.suggested_vendor_id ? String(pr.suggested_vendor_id) : '',
                        justification:       pr.justification || '',
                        remarks:             pr.remarks || '',
                        line_items: (pr.line_items || []).map((l, i) => ({
                            line_number:          l.line_number || i + 1,
                            material_id:          l.material_id ? String(l.material_id) : '',
                            material_type:        l.material?.material_type || '',
                            item_name:            l.item_name,
                            description:          l.description,
                            quantity:             l.quantity,
                            uom_id:               l.uom_id ? String(l.uom_id) : '',
                            estimated_unit_price: l.estimated_unit_price || 0,
                            estimated_total:      (parseFloat(l.quantity)||0) * (parseFloat(l.estimated_unit_price)||0),
                            warehouse_id:         l.warehouse_id ? String(l.warehouse_id) : '',
                            purpose:              l.purpose || '',
                            sort_order:           l.sort_order || i + 1,
                        })),
                    };
                }
            } catch (e) { console.error('Failed to load PR:', e); }
        },

        // Convert any date string to YYYY-MM-DD for <input type="date">
        toDateInput(val) {
            if (!val) return '';
            return val.substring(0, 10);
        },

        onDeptChange() {
            const dept = this.departments.find(d => d.id == this.form.department_id);
            this.form.cost_center_code = dept?.cost_center_code || '';
        },

        addLineItem() {
            const n = this.form.line_items.length + 1;
            this.form.line_items.push({
                line_number: n, material_id: '', material_type: '', item_name: '',
                description: '', quantity: 1, uom_id: '', estimated_unit_price: 0,
                estimated_total: 0, warehouse_id: '', purpose: '', sort_order: n,
            });
        },

        removeLineItem(index) {
            this.form.line_items.splice(index, 1);
            this.form.line_items.forEach((item, i) => { item.line_number = i + 1; item.sort_order = i + 1; });
        },

        onMaterialSelect(index) {
            const item = this.form.line_items[index];
            const material = this.materials.find(m => m.id == item.material_id);
            if (!material) return;
            item.item_name            = material.material_name || '';
            item.material_type        = material.material_type || '';
            item.uom_id               = material.uom_id || '';
            item.estimated_unit_price = parseFloat(material.standard_cost) || 0;
            item.warehouse_id         = material.default_warehouse_id || '';
            this.calcTotal(index);
        },

        calcTotal(index) {
            const item = this.form.line_items[index];
            item.estimated_total = (parseFloat(item.quantity)||0) * (parseFloat(item.estimated_unit_price)||0);
        },

        grandTotal() {
            return this.form.line_items.reduce((s, i) => s + (parseFloat(i.estimated_total)||0), 0);
        },

        formatCurrency(val) {
            return '₹ ' + (parseFloat(val)||0).toFixed(2);
        },

        async submitForm(status) {
            this.errorMsg = '';
            if (this.form.line_items.length === 0) {
                this.errorMsg = 'Please add at least one line item.';
                return;
            }
            this.saving = true;
            try {
                const payload = { ...this.form, status, suggested_vendor_id: this.form.suggested_vendor_id || null };
                const res = await fetch('/api/v1/purchase-requisitions/' + this.prId, {
                    method: 'PUT',
                    credentials: 'same-origin',
                    headers: {
                        'Content-Type': 'application/json',
                        'Accept': 'application/json',
                        'X-CSRF-TOKEN': document.querySelector('meta[name="csrf-token"]').getAttribute('content'),
                    },
                    body: JSON.stringify(payload),
                });
                const data = await res.json();
                if (!res.ok || !data.success) {
                    const details = data.error?.details;
                    this.errorMsg = details ? Object.values(details).flat().join(' | ') : (data.message || 'Failed to update.');
                    return;
                }
                window.location.href = '{{ url("/org/{$organization->org_slug}/procurement/purchase-requisition") }}';
            } catch (e) {
                console.error(e);
                this.errorMsg = 'Network error. Please try again.';
            } finally {
                this.saving = false;
            }
        },
    }
}
</script>
@endsection
